name: Build and Push YouTube Downloader

on:
  push:
    branches: [ publish ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/yt-to-rubika:latest
            ghcr.io/${{ github.repository }}/yt-to-rubika:${{ github.sha }}
      

      # - name: Deploy via SSH to Server
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     passphrase: ${{ secrets.SERVER_PASS_PHRASE }}
      #     port: ${{ secrets.SERVER_PORT || '22' }}
      #     script: |
      #       cd /opt/stacks/yt-to-rubika

      #       # Pull the latest Docker image
      #       docker compose pull

      #       # Restart the service with the new image
      #       docker compose up -d --remove-orphans

      #       # Clean up old images to save space
      #       #docker image prune -f